source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '10.0'

target 'MBoxReposDemo_Example' do
  pod 'MBoxReposDemo', :path => '../'

  pod 'SnapKit', '~> 5.0.0'
  pod 'Alamofire', '~> 5.4'

  target 'MBoxReposDemo_Tests' do
    inherit! :search_paths
    
  end
end
