source 'https://cdn.cocoapods.org/'

use_frameworks!
project "MBoxReposDemo.xcodeproj"
platform :ios, '10.0'

target 'MBoxReposDemo_Example' do
  pod 'MBoxReposDemo', :path => '../'

  pod 'Alamofire', '5.4.3'
  pod 'SwiftyJSON', '5.0.1'

  target 'MBoxReposDemo_Tests' do
    inherit! :search_paths
    
  end
end
